# Generated by Django 4.0 on 2022-11-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default=None, verbose_name='текст комментария'),
        ),
    ]
