# Generated by Django 4.0 on 2022-11-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0003_comments_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-like']},
        ),
        migrations.AlterField(
            model_name='events',
            name='like',
            field=models.IntegerField(default=0, verbose_name='количество лайков'),
        ),
        migrations.AlterModelTable(
            name='comments',
            table='Комментарии',
        ),
        migrations.AlterModelTable(
            name='events',
            table='События',
        ),
    ]
