# Generated by Django 4.0 on 2022-11-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0004_alter_events_options_alter_events_like_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-likes']},
        ),
        migrations.RenameField(
            model_name='events',
            old_name='like',
            new_name='likes',
        ),
    ]
