# Generated by Django 4.0 on 2022-11-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_remove_customuser_like'),
        ('fase', '0005_alter_events_options_rename_like_events_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-like']},
        ),
        migrations.RenameField(
            model_name='events',
            old_name='likes',
            new_name='like',
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fase.events', verbose_name='событие')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='back.customuser', verbose_name='кто лайкал')),
            ],
        ),
    ]
