# Generated by Django 4.0 on 2022-11-19 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0006_alter_events_options_rename_likes_events_like_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='район')),
            ],
            options={
                'db_table': 'Районы',
            },
        ),
        migrations.AlterModelTable(
            name='likes',
            table='Лайки',
        ),
        migrations.AddField(
            model_name='events',
            name='district',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fase.district'),
        ),
    ]
