# Generated by Django 4.0 on 2022-11-20 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0007_district_alter_likes_table_events_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='coordinate',
            field=models.CharField(blank=True, max_length=255, verbose_name='координаты'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='events',
            name='district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fase.district'),
        ),
        migrations.AlterField(
            model_name='events',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество лайков'),
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.FileField(blank=True, upload_to='photo/%Y/%m.%d/', verbose_name='фото проблемы'),
        ),
        migrations.AlterField(
            model_name='events',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='название'),
        ),
    ]
