# Generated by Django 4.0 on 2022-11-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0008_alter_events_coordinate_alter_events_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('A', 'Принятый'), ('R', 'Отказано'), ('С', 'Архив')], default='', max_length=1, verbose_name='статус'),
        ),
    ]
