# Generated by Django 4.0 on 2022-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0009_events_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('A', 'Принятый'), ('R', 'Отказано'), ('C', 'Архив')], default='', max_length=1, verbose_name='статус'),
        ),
    ]
