# Generated by Django 4.0 on 2022-11-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0011_alter_events_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(blank=True, upload_to='photo/%Y/%m.%d/', verbose_name='фото проблемы')),
            ],
        ),
    ]
