# Generated by Django 4.0 on 2022-11-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fase', '0005_alter_events_options_rename_like_events_likes'),
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='like',
            field=models.ManyToManyField(to='fase.Events', verbose_name='лайки'),
        ),
    ]
