# Generated by Django 4.0 on 2022-11-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_customuser_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='like',
        ),
    ]
